name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
      
    - uses: alex-ac/github-action-ssh-docker-compose@master
      name: Docker-Compose Remote Deployment
      with:
        ssh_host: 10.14.11.16
        ssh_port: 22
        ssh_private_key: ${{ secrets.SSH_KEY }}
        ssh_user: dominik.osuch
        docker_compose_prefix: infrastructure/docker-compose.yml  
